### PR TITLE
Fix issue #107

### LINKED ISSUE #107: Python 3 compatible code example for TempURL
https://developer.rackspace.com/docs/cloud-files/v1/use-cases/public-access-to-your-cloud-files-account/#create-the-tempurl has a Python2 code example.

Since Python2 is EOL after 2020, we recommend a Python3 code example. Not perfect by any means, but as a start:

```    expires = int(time() + duration_in_seconds)
    method = method.upper()
    base_url, object_path = object_url.split('/v1/')
    object_path = '/v1/' + object_path
    #  print object_url
    hmac_body = '%s\n%s\n%s' % (method, expires, object_path)
    temp_url_key_bytes = bytes(temp_url_key , 'latin-1')
    hmac_body_bytes = bytes(hmac_body, 'latin-1')
    temp_url_sig = hmac.new(temp_url_key_bytes, hmac_body_bytes, sha256).hexdigest()
    s = '{object_url}?temp_url_sig={temp_url_sig}&temp_url_expires={expires}'
    temp_url = s.format(object_url=object_url, temp_url_sig=temp_url_sig, expires=expires)

### PR DESCRIPTION
**Pull request by cyrichardson**
Fix #107

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-1327902318/docs/cloud-files/v1/)

**Comment by cyrichardson** [comment]
@inflatador Please review - certainly not sure I have it right.
https://staging.developer.rackspace.com/build-1327902318/docs/cloud-files/v1/use-cases/public-access-to-your-cloud-files-account/#create-the-tempurl

**Comment by inflatador** [comment]
+1 looks good to me . Thanks @cyrichardson  !

**Comment by cyrichardson** [comment]
Thanks for reviewing so quickly, @inflatador!

**Pull request merged**
