### PR TITLE
Update put-cdn-enable-and-cdn-disable-a-container-v1-account-container

### PR DESCRIPTION
**Pull request by kylelaffoon**
Fix typo

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-88277531a0/docs/cloud-files/v1/developer-guide/). :bow:

**Comment by cyrichardson** [comment]
Sorry, @kylelaffoon. I should have noticed that one of the " is not correct. Please change “name": "cloudFilesCDN" to "name": "cloudFilesCDN". (That first " is curly rather than straight.)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-48850162cb/docs/cloud-files/v1/developer-guide/).

**Comment by cyrichardson** [comment]
LGTM. Merging.

**Pull request merged**
